#cloud-config
users: # Benutzerkonfigurationen
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Gruppen, denen der Benutzer angehört
    home: /home/ubuntu # Home-Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # Liste der autorisierten SSH-Schlüssel
      - ssh-rsa MIIEpQIBAAKCAQEAuNYZIlVvFT2zNfjr4B1jJ5N0g2b0XSfNlv4F1zq/Z9GsAbOBHtvojS+6YI8RiLGsEXRG5MZomIMf9f6RRY6IQET/VdezRoUFt1B/25xPmf6mTuAyd8YgKkpghpNtWfJ5FVh8VloPRCOMppEgUdaWtGArsX5L4Zy7Tq2HK+2C67KTFF4kmVvxO7cqTX3F8eaLCICgePeoLxi3xMgujHxEhyOsUwq8cPqsEumqQ6ddILvDgEEU28WJ5dy6In3SqOdTTHgIOQntGV6kiJIIjA5Tfo/iGLNMTjYHg/qc4Q+BcwSsoAERKURr8hk1g2bziF3xE3xbvF5xpr8m/MOojFK6DwIDAQABAoIBAQC0DCHZlv0o5LxQQ9SIsDepEnL5mO1KXP5gKbvIxzoxyEVUNuX9CFvERAy6CEMdM20YZ3qzWS4D+h7FAh/CcK/6YvuSRBYnCGbkBW82nlHQAQVBahTfJUipyV+zV6K6bn5SM6qSdxHN3w8gJdgkv/J3bALD1/HUqFawskosmSThr54XqP56jSF8FZowzQd/ESO1wa9NbWJmgGC+Co4T296Pf7tQoBl1lZkMWXizseFrcf8I0fDVVILMrxtFNUZn2Yzb4BRq7Wl1O0FOAQVovYsjM7rRQfGQ+rwsjVBweYY/1yyVRdTa6x/LJF2bHgVOiFXaRmTacyiFm8yAA6Ju/VhBAoGBAObvOH7VQXp9zvMhkQbHez1EdXp2nKZ93s6SIMrq6XJ0S/uNOwM7z29t7/OnEWAXfBuY4gj4ypvfz9Z00t+sDB6xYWmnwXYLZu45M+e0kRy4LsD/1IfiQhJPnCp0mmpVg3VsH6OB2zb80YKrEh9AuiP5IaoPJK3JtA7dnwY7EFcvAoGBAMzl karol-1 # Autorisierter SSH-Schlüssel für den Benutzer
ssh_pwauth: false # Passwortauthentifizierung für SSH deaktiviert
disable_root: false # Root-Benutzer nicht deaktiviert
package_update: true # Pakete beim Booten aktualisieren
packages: # Liste der zu installierenden Pakete
  - curl # Paket: curl
  - wget # Paket: wget
