#cloud-config
users: # Benutzerkonfigurationen
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Gruppen, denen der Benutzer angehört
    home: /home/ubuntu # Home-Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # Liste der autorisierten SSH-Schlüssel
      - ssh-rsa MIIEpQIBAAKCAQEAuNYZIlVvFT2zNfjr4B1jJ5N0g2b0XSfNlv4F1zq/Z9GsAbOB
HtvojS+6YI8RiLGsEXRG5MZomIMf9f6RRY6IQET/VdezRoUFt1B/25xPmf6mTuAy
d8YgKkpghpNtWfJ5FVh8VloPRCOMppEgUdaWtGArsX5L4Zy7Tq2HK+2C67KTFF4k
mVvxO7cqTX3F8eaLCICgePeoLxi3xMgujHxEhyOsUwq8cPqsEumqQ6ddILvDgEEU
28WJ5dy6In3SqOdTTHgIOQntGV6kiJIIjA5Tfo/iGLNMTjYHg/qc4Q+BcwSsoAER
KURr8hk1g2bziF3xE3xbvF5xpr8m/MOojFK6DwIDAQABAoIBAQC0DCHZlv0o5LxQ
Q9SIsDepEnL5mO1KXP5gKbvIxzoxyEVUNuX9CFvERAy6CEMdM20YZ3qzWS4D+h7F
Ah/CcK/6YvuSRBYnCGbkBW82nlHQAQVBahTfJUipyV+zV6K6bn5SM6qSdxHN3w8g
Jdgkv/J3bALD1/HUqFawskosmSThr54XqP56jSF8FZowzQd/ESO1wa9NbWJmgGC+
Co4T296Pf7tQoBl1lZkMWXizseFrcf8I0fDVVILMrxtFNUZn2Yzb4BRq7Wl1O0FO
AQVovYsjM7rRQfGQ+rwsjVBweYY/1yyVRdTa6x/LJF2bHgVOiFXaRmTacyiFm8yA
A6Ju/VhBAoGBAObvOH7VQXp9zvMhkQbHez1EdXp2nKZ93s6SIMrq6XJ0S/uNOwM7
z29t7/OnEWAXfBuY4gj4ypvfz9Z00t+sDB6xYWmnwXYLZu45M+e0kRy4LsD/1Ifi
QhJPnCp0mmpVg3VsH6OB2zb80YKrEh9AuiP5IaoPJK3JtA7dnwY7EFcvAoGBAMzl
/OJpk8PMftVT7K5vaw5Yv4B/ExIBeyJP1o0lW3SlJTnvsvqT0JQLZR+SL3ZIqZq/
V7mz66F6cYryJ2RK0QqEqw9FYHW6iO5rC0QkvVkIvCBJg3VRqmZxvMOnIQ5V8Ock
upL2/cH5zov+TewRySpnOQAy5dqnWdoXIWJTcRMhAoGANoTjYY4XF0P8R4n1IxSV
E7HFylOWR/gPUdVNyJoM4uhxx8Ff3TORlUzvCSa4A2eH9TvyoQubSZFdD9QktIl5
kwVtafQgyC2I71Sx3FHUsGMLJqU/F5Vi48/Hnn5ItjHaBy6viXputlyZWa/pZ1dw
mm2GdQ9+KUklKR1JHb9z7CECgYEAwF7lkEUDYH8sTWlf+13MK0oTcbbc1rjhPJOs
ohQCy38Jdl2fsjb5SyVvqbZ8LReHdSxUVpufjJoC5Cr55OWBYdixKcM/Dwk06nNB
vpan12GmDsI2U/16eHgse5z8IhN5++m16alPEcFRtInr6snADrmfAJrIxwL8DxBM
XZ5tuUECgYEAs/pPZ0qou33fTvbKkjxvaIkQzzItd0sAYRRz/DKpPZUF8/OkXKyE
xBhtfJvlXoYlVvNXcznD9hkiEYxrpUdManl8cggHeAWbjfkehNTY0J/tK2CM3PPr
EIxLZj00fxbEHTMSvUtr/JWvHfW2ckLDmxRtJURz+jFMs8JbOOnTxpY= karol-1 # Autorisierter SSH-Schlüssel für den Benutzer
ssh_pwauth: false # Passwortauthentifizierung für SSH deaktiviert
disable_root: false # Root-Benutzer nicht deaktiviert
package_update: true # Pakete beim Booten aktualisieren
packages: # Liste der zu installierenden Pakete
  - curl # Paket: curl
  - wget # Paket: wget

